<a href="https://colab.research.google.com/github/Aniketpatil1992/Machine-learning/blob/main/simple%20and%20multiple%20linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# import seaborn as sns

In [4]:
#Importing the dataset
data = pd.read_csv("/content/Advertising_data.csv.csv")
data.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   2210
1   44.5   39.3       45.1   1040
2   17.2   45.9       69.3    930
3  151.5   41.3       58.5   1850
4  180.8   10.8       58.4   1290

Simple linear regression


Inititializing the variables


In [5]:
x=data['TV'].values.reshape(-1,1)
y=data['sales'].values.reshape(-1,1)


# Splitting dataset into training and testing dataset


In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=45)

# Fitting linear regression to our training set to train our model

In [7]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

Predicting the test set result

In [8]:
y_pred=reg.predict(x_test)

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)


0.5299030898659628

In [10]:
output = reg.predict([[300.06]])
output

array([[2137.98180361]])

In [11]:
#Intercept
reg.intercept_

array([680.39560881])

In [12]:
reg.coef_

array([[4.85764912]])

# Multiple Linear Regression

In [14]:
#Initiating the variables
X = data.drop(['sales'], axis = 1)
y = data['sales'].values.reshape(-1,1)

In [15]:
#Splitting data into training, testing datase
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
#Fitting Linear regression to our training set
from sklearn.linear_model import LinearRegression
multiple_reg = LinearRegression()
multiple_reg.fit(X_train, y_train)

LinearRegression()

In [17]:
#Testing
y_pred = multiple_reg.predict(X_test)

In [18]:
#Taking the input from the user
print("Enter the ammount you will invest on:")
tv = float(input("TV : "))
radio = float(input("Radio : "))
newspaper = float(input("Newspaper : "))

#predicting the sales with respect to the inputs
output = multiple_reg.predict([[tv,radio,newspaper]])
print("you will get Rs{:.3f} sales by advertising Rs{} on TV, Rs{} on Radio and Rs{} on newspaper."\
      .format(output[0][0] if output else "not predictable",tv,radio,newspaper))

Enter the ammount you will invest on:
TV : 100
Radio : 200.2
Newspaper : 50
you will get Rs4546.692 sales by advertising Rs100.0 on TV, Rs200.2 on Radio and Rs50.0 on newspaper.


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
